---
- hosts: all
  become: true
  vars:
    php_version: "7.2"
    es_version: "1.7.1"
    mysql_root_password: "vagrant"
    node_major_version: 6
    domain: "os2display.vm"

  pre_tasks:

  post_tasks:
    - include: tasks/nginx.yml
    - include: tasks/sites.yml

  roles:
    - common
    - mariadb_server
    - nginx
    - php72
    - composer
    - nodejs
    - memcached
    - redis
    - java7
    - elasticsearch
