---
- hosts: all
  become: true
  vars:
    php_version: "5.6"
    es_version: "1.7.1"
    mysql_root_password: "vagrant"
    node_major_version: 6
    domain: "os2display.vm"

  pre_tasks:
    # Tasks that shold be run before roles.

  post_tasks:
    # Tasks that shold be run after roles.
    - include: tasks/nginx.yml
    - include: tasks/sites.yml

  roles:
    - common
    - mysql
    - nginx
    - php56
    - composer
    - nodejs
    - memcached
    - redis
    - java7
    - elasticsearch
#    - mariadb_server
#    - php72
