---
- name: Install
  apt: pkg=mysql-server state=latest update_cache=yes
  tags: mysql

- name: Install python-mysqldb
  apt: pkg=python-mysqldb state=latest update_cache=yes
  tags: mysql

- name: Update root password for all root accounts from local servers
  mysql_user: name=root host={{ item }} password={{ mysql_root_password }}
  when: mysql_root_password is defined
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
  tags: mysql

- name: Copy .my.cnf file with root password credentials - root
  template: src=root.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
  when: mysql_root_password is defined
  tags: mysql

- name: Copy .my.cnf file with root password credentials - vagrant
  template: src=root.cnf.j2 dest=/home/vagrant/.my.cnf owner=vagrant mode=0600
  when: mysql_root_password is defined
  tags: mysql

- name: Remove the test database
  mysql_db: name=test state=absent
  tags: mysql

- name: Ensure service is running
  service: name=mysql state=started
  tags: mysql
